name: test
on: [push, pull_request]
# defaults:
#   run:
#     working-directory: /home/runner/work/lcov/lcov/main
jobs:
  test:
    name: Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - name: Clone default branch
        uses: actions/checkout@v2
        with:
          path: main
      # -----------------------------------------------------------------------
      - name: Clone docs branch
        uses: actions/checkout@v2
        with:
          path: docs
          ref: docs
      # -----------------------------------------------------------------------
      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      # -----------------------------------------------------------------------
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        # working-directory: /home/runner/work/lcov/lcov/main
        with:
          path: main/node_modules
          key: ${{ matrix.node }}-${{ matrix.os }}-${{ hashFiles('package.json') }}
      # -----------------------------------------------------------------------
      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
        working-directory: /home/runner/work/lcov/lcov/main
      # -----------------------------------------------------------------------
      - name: Coverage
        run: |
          output=$(npm run test:cov | tee /dev/stderr)
          echo "coverage='$(echo $output | tr -d "\n")'" >> $GITHUB_ENV
        working-directory: /home/runner/work/lcov/lcov/main
      # -----------------------------------------------------------------------
      - name: Push coverage
        uses: outofindex/lcov@master
        with:
          coverage: ${{ env.coverage }}
          token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: /home/runner/work/lcov/lcov/main
      # -----------------------------------------------------------------------
      - name: Test
        run: |
          git --version
          git branch
          git config --list
