name: test
on: [push, pull_request]
jobs:
  test:
    name: Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.node }}-${{ matrix.os }}-${{ hashFiles('package.json') }}
      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Coverage
        run: |
          output=$(npm run test:cov | tee /dev/stderr)
          echo "coverage='$(echo $output | tr -d "\n")'" >> $GITHUB_ENV
      - name: Push coverage
        uses: outofindex/lcov@master
        with:
          coverage: ${{ env.coverage }}
