name: test
on: [push, pull_request]
jobs:
  test:
    name: Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - name: Clone default branch
        uses: actions/checkout@v2
        with:
          path: main
      # -----------------------------------------------------------------------
      - name: Clone docs branch
        uses: actions/checkout@v2
        with:
          path: docs
          ref: docs
      # -----------------------------------------------------------------------
      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      # -----------------------------------------------------------------------
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: main/node_modules
          key: ${{ matrix.node }}-${{ matrix.os }}-${{ hashFiles('package.json') }}
      # -----------------------------------------------------------------------
      - name: Install deps
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          cd $GITHUB_WORKSPACE/main
          npm install
      # -----------------------------------------------------------------------
      - name: Coverage report
        run: |
          cd $GITHUB_WORKSPACE/main
          output=$(npm run test:cov | tee /dev/stderr)
          echo "coverage='$(echo $output | tr -d "\n")'" >> $GITHUB_ENV
      # -----------------------------------------------------------------------
      - name: Generate badge
        uses: outofindex/lcov@master
        with:
          coverage: ${{ env.coverage }}
          token: ${{ secrets.GITHUB_TOKEN }}
      # -----------------------------------------------------------------------
      - name: Copy report and badge
        run: |
          mkdir -p $GITHUB_WORKSPACE/docs/coverage
          cp $GITHUB_WORKSPACE/main/coverage/lcov-report/* $GITHUB_WORKSPACE/docs/coverage/
          cp $GITHUB_WORKSPACE/coverage.svg $GITHUB_WORKSPACE/docs/coverage/badge.svg
      # -----------------------------------------------------------------------
      - name: Push to docs branch
        run: |
          cd $GITHUB_WORKSPACE/docs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Update coverage'
          git push
